[package]
name = "sova-payload"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
sova-cli.workspace = true
sova-node.workspace = true
sova-evm.workspace = true

reth.workspace = true
reth-chainspec.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true

eyre.workspace = true
