[package]
name = "sova"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sova-reth.workspace = true

# reth
reth-cli.workspace = true
reth-cli-util.workspace = true
reth-tracing.workspace = true
reth-node-builder.workspace = true
reth-optimism-cli.workspace = true
reth-optimism-node.workspace = true

# misc
clap.workspace = true
eyre.workspace = true

[[bin]]
name = "sova-reth"
path = "src/main.rs"