[package]
name = "sova-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sova-chainspec.workspace = true
sova-cli.workspace = true
sova-evm.workspace = true
sova-node.workspace = true

reth-cli-util.workspace = true
reth-tracing.workspace = true
reth-optimism-cli.workspace = true

clap.workspace = true
eyre.workspace = true

[[bin]]
name = "sova-reth"
path = "src/main.rs"