[package]
name = "sova-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sova-cli.workspace = true
sova-node.workspace = true

reth.workspace = true
reth-cli-util.workspace = true
reth-tracing.workspace = true

clap.workspace = true

[[bin]]
name = "sova-reth"
path = "src/main.rs"