sequenceDiagram
    participant Dapp
    participant Reth
    participant Indexer
    participant Sequencer
    participant BTC_Node

    Dapp->>Reth: Initiate Withrdaw on Sova
    Reth->>Indexer: Fetch spendable UTXOs for uBTC
    Indexer->>Reth: Send spendable UTXOs
    Note over Reth: Build a TX with Ins & Outs
    Reth->>Sequencer: call signTransaction with In & Outs & Eth Addr
    Note over Sequencer: Sign TX
    Sequencer->>BTC_Node: Submit TX
    Sequencer->>Reth: Send txid
    Note over Reth: Emit txid in Event
    Sequencer->>Indexer: Send txid
    Note over Indexer: Mark UTXO as spent
    Note over Indexer: Store new spendable UTXOs
    Dapp->>BTC_Node: get txid status