[package]
name = "corsa-reth"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# corsa-reth
corsa-cli.workspace = true
corsa-config.workspace = true
corsa-bitcoin-precompiles.workspace = true

# reth
reth.workspace = true
reth-chainspec.workspace = true
reth-evm-ethereum.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-tracing.workspace = true

# tokio
tokio.workspace = true

# misc
clap.workspace = true
eyre.workspace = true
parking_lot.workspace = true

[[bin]]
name = "corsa-reth"
path = "src/main.rs"
