[package]
name = "corsa-bitcoin-client"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
# corsa-reth
corsa-config.workspace = true

# btc
bitcoin.workspace = true
bitcoincore-rpc.workspace = true