# Publishes the Docker image.

name: docker

on:
  push:
    branches: ["main"]
    tags:
      - v*
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.repository_owner }}/sova-reth
  IMAGE_NAME: ${{ github.repository_owner }}/sova-reth
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE_NAME: ghcr.io/sovanetwork/sova-reth # repository name must be lowercase
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  extract-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Extract version (if main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "VERSION=latest" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=" >> $GITHUB_ENV
      - name: Extract version (if tagged release)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=" >> $GITHUB_ENV
    outputs:
      VERSION: ${{ env.VERSION }}
      VERSION_SUFFIX: ${{ env.VERSION_SUFFIX }}

  build:
    name: build and push
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@cross
      - name: Log in to Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --use --name cross-builder
      - name: Build and push sova-reth image, tag as "latest"
        run: make PROFILE=release docker-build-push-latest
      - name: Build and push sova-reth image
        run: make PROFILE=release docker-build-push